# Generated by Django 3.0.8 on 2020-08-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'hub_models',
            },
        ),
        migrations.CreateModel(
            name='HubLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('is_used', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.HubModel')),
            ],
            options={
                'db_table': 'hub_licenses',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('password', models.TextField(editable=False)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hub.HubLicense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
    ]
