# Generated by Django 3.0.8 on 2020-11-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20201112_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hublicense',
            name='is_used',
        ),
    ]
