# Generated by Django 3.0.8 on 2021-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_hublicense_is_used'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hub',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='hub_hub_unique_name_per_user'),
        ),
    ]
