# Generated by Django 3.0.8 on 2021-05-02 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20210502_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
