# Generated by Django 3.0.8 on 2020-11-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('dimension', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensormodel',
            name='dimension',
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.SensorType'),
        ),
    ]
