# Generated by Django 3.0.8 on 2020-11-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20201111_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensortype',
            table='sensor_types',
        ),
    ]
