# Generated by Django 3.0.8 on 2020-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20201111_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
