# Generated by Django 3.0.8 on 2020-11-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_remove_sensor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlicense',
            name='is_used',
        ),
    ]
